import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1742946782061 implements MigrationInterface {
    name = 'Init1742946782061'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recruitment_post_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "problem_finished_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_938c0a27255637bde919591888f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_18a836fd4614ea6282418239fa" ON "applications" ("user_id", "recruitment_post_id") `);
        await queryRunner.query(`CREATE TABLE "applications_problems" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "result" jsonb, "application_id" uuid, "problem_id" uuid, CONSTRAINT "PK_53aa2b732f257029256057125fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recruitment_posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL, "title" character varying NOT NULL, "job_position" character varying NOT NULL, "location" character varying NOT NULL, "work_type" character varying NOT NULL, "job_type" character varying NOT NULL, "description" text NOT NULL, "page_user_id" uuid, CONSTRAINT "PK_d38c8d3adff01b768dfd5250486" PRIMARY KEY ("id")); COMMENT ON COLUMN "recruitment_posts"."description" IS 'Markdown formatted text for job description'`);
        await queryRunner.query(`CREATE TABLE "problems" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying NOT NULL, "content" character varying NOT NULL, "page_id" uuid, CONSTRAINT "PK_b3994afba6ab64a42cda1ccaeff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "problems_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "result" jsonb, "problem_id" uuid, "user_id" uuid, CONSTRAINT "PK_6b893533ff3cf559e8b7a63f731" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "problems_recruitment_posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "problem_id" uuid, "recruitment_post_id" uuid, CONSTRAINT "PK_ad955bc0d76bad986f0205035a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "owner_type" character varying NOT NULL, "owner_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file_data" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_da96729a8b113377cfb6a62439c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ddb83c9599ff3fc19dfef0692c" ON "assets" ("owner_id", "type", "owner_type") `);
        await queryRunner.query(`CREATE TYPE "public"."pages_status_enum" AS ENUM('started', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "pages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "content" character varying, "address" character varying NOT NULL, "url" character varying NOT NULL, "email" character varying NOT NULL, "status" "public"."pages_status_enum" NOT NULL DEFAULT 'started', CONSTRAINT "UQ_3edf1d1cf08691a0a432589ac93" UNIQUE ("email"), CONSTRAINT "PK_8f21ed625aa34c8391d636b7d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3edf1d1cf08691a0a432589ac9" ON "pages" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."pages_users_role_enum" AS ENUM('MEMBER', 'OPERATOR', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "pages_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "role" "public"."pages_users_role_enum" NOT NULL DEFAULT 'MEMBER', "start_date" date, "end_date" date, "page_id" uuid, "user_id" uuid, CONSTRAINT "PK_733d2c569fa8a65acfc63f5c454" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comment_statistics" ("comment_id" uuid NOT NULL, "react_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_3bbda74aca343bbc36f039330cd" PRIMARY KEY ("comment_id"))`);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "content" text NOT NULL, "user_id" uuid, "post_id" uuid, "statistics_comment_id" uuid, CONSTRAINT "REL_6a8198b0a3bf6fd4584bc0932f" UNIQUE ("statistics_comment_id"), CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post_statistics" ("post_id" uuid NOT NULL, "comment_count" integer NOT NULL DEFAULT '0', "react_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_ac42035005eced3155c787015fe" PRIMARY KEY ("post_id"))`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "content" text NOT NULL, "comment_count" integer NOT NULL DEFAULT '0', "react_count" integer NOT NULL DEFAULT '0', "author_id" uuid, CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "user_id" uuid NOT NULL, "target_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "target_type" character varying NOT NULL, CONSTRAINT "PK_e9a4e287e70372a267d7f363a12" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d95caa497b2292c730dd45d900" ON "reacts" ("target_id", "target_type", "user_id") `);
        await queryRunner.query(`CREATE TABLE "friends" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "source_id" uuid, "target_id" uuid, CONSTRAINT "PK_65e1b06a9f379ee5255054021e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "friends_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "is_available" boolean NOT NULL DEFAULT true, "source_id" uuid, "target_id" uuid, CONSTRAINT "PK_44b734b20b071c5d930b63c9b3c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "content" character varying NOT NULL, "conversation_id" uuid, "sender_user_id" uuid, "sender_page_id" uuid, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying, "is_group" boolean NOT NULL DEFAULT false, "last_message_id" uuid, CONSTRAINT "REL_a53679287450d522a3f700088e" UNIQUE ("last_message_id"), CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "conversation_id" uuid, "user_id" uuid, "page_id" uuid, CONSTRAINT "PK_1cda06c31eec1c95b3365a0283f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('USER', 'ADMIN')`);
        await queryRunner.query(`CREATE TYPE "public"."users_gender_enum" AS ENUM('Male', 'Female')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'USER', "email" character varying NOT NULL, "password" character varying NOT NULL, "date_of_birth" date, "gender" "public"."users_gender_enum", "major" character varying, "desired_job_position" character varying, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "follows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "page_id" uuid, "user_id" uuid, CONSTRAINT "PK_8988f607744e16ff79da3b8a627" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "meta" jsonb NOT NULL DEFAULT '{}', "is_readed" boolean NOT NULL DEFAULT false, "user_id" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "conversation_read_status" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "conversation_id" uuid, "user_id" uuid, "last_read_message_id" uuid, CONSTRAINT "PK_7fdc971e4203697fc5197153d64" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_9e7594d5b474d9cbebba15c1ae7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_5a18e8914a1a55ae3be14764bd0" FOREIGN KEY ("recruitment_post_id") REFERENCES "recruitment_posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications_problems" ADD CONSTRAINT "FK_f2effc129801d702f1cde963896" FOREIGN KEY ("application_id") REFERENCES "applications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications_problems" ADD CONSTRAINT "FK_7d017d4fe48c00bacc849aaac12" FOREIGN KEY ("problem_id") REFERENCES "problems_recruitment_posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recruitment_posts" ADD CONSTRAINT "FK_2a74bde895d01c06cb61456062e" FOREIGN KEY ("page_user_id") REFERENCES "pages_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "problems" ADD CONSTRAINT "FK_d70540d9e2b2264909c84148825" FOREIGN KEY ("page_id") REFERENCES "pages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "problems_users" ADD CONSTRAINT "FK_6bf973a1955c5f27079f446155c" FOREIGN KEY ("problem_id") REFERENCES "problems"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "problems_users" ADD CONSTRAINT "FK_8776019c9132730ba3af6abe99b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "problems_recruitment_posts" ADD CONSTRAINT "FK_3cd0e939eeacc5e3944a29fff7b" FOREIGN KEY ("problem_id") REFERENCES "problems"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "problems_recruitment_posts" ADD CONSTRAINT "FK_c38fcf53c82ab17f72db6f748cd" FOREIGN KEY ("recruitment_post_id") REFERENCES "recruitment_posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_users" ADD CONSTRAINT "FK_1d9fdc44c36ca56b4f81ca1bf14" FOREIGN KEY ("page_id") REFERENCES "pages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_users" ADD CONSTRAINT "FK_020256cb575d3ff6302315630b6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_statistics" ADD CONSTRAINT "FK_3bbda74aca343bbc36f039330cd" FOREIGN KEY ("comment_id") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_259bf9825d9d198608d1b46b0b5" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_6a8198b0a3bf6fd4584bc0932f8" FOREIGN KEY ("statistics_comment_id") REFERENCES "comment_statistics"("comment_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_statistics" ADD CONSTRAINT "FK_ac42035005eced3155c787015fe" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_312c63be865c81b922e39c2475e" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reacts" ADD CONSTRAINT "FK_dfa61fb53fdd11941a52f05351e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friends" ADD CONSTRAINT "FK_23fac43a0543182b1f1bdd644c7" FOREIGN KEY ("source_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friends" ADD CONSTRAINT "FK_7228831e05ab7a5a7bf260c5ce6" FOREIGN KEY ("target_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friends_requests" ADD CONSTRAINT "FK_7914ec6460702eabeddbd9b77f8" FOREIGN KEY ("source_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friends_requests" ADD CONSTRAINT "FK_e06dd257e072a8aa3c4299ec33e" FOREIGN KEY ("target_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_b183972e0b84c9022884433195e" FOREIGN KEY ("sender_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2b34d74ea416e099ba1525da6e6" FOREIGN KEY ("sender_page_id") REFERENCES "pages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_a53679287450d522a3f700088e9" FOREIGN KEY ("last_message_id") REFERENCES "messages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participants" ADD CONSTRAINT "FK_de8978490834e2e9cb3c3fc8066" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participants" ADD CONSTRAINT "FK_1427a77e06023c250ed3794a1ba" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participants" ADD CONSTRAINT "FK_f6032995d645f86cbee8add6bb2" FOREIGN KEY ("page_id") REFERENCES "pages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_b7ce63a5ae8f154be7de989ea12" FOREIGN KEY ("page_id") REFERENCES "pages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_941d172275662c2b9d8b9f4270c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_read_status" ADD CONSTRAINT "FK_bb2a949a0c9921191da9dc802b2" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_read_status" ADD CONSTRAINT "FK_31eaeae4f37db9d8e8d77740b92" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_read_status" ADD CONSTRAINT "FK_6bb442e781de2c9669799ad84de" FOREIGN KEY ("last_read_message_id") REFERENCES "messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "conversation_read_status" DROP CONSTRAINT "FK_6bb442e781de2c9669799ad84de"`);
        await queryRunner.query(`ALTER TABLE "conversation_read_status" DROP CONSTRAINT "FK_31eaeae4f37db9d8e8d77740b92"`);
        await queryRunner.query(`ALTER TABLE "conversation_read_status" DROP CONSTRAINT "FK_bb2a949a0c9921191da9dc802b2"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_941d172275662c2b9d8b9f4270c"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_b7ce63a5ae8f154be7de989ea12"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP CONSTRAINT "FK_f6032995d645f86cbee8add6bb2"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP CONSTRAINT "FK_1427a77e06023c250ed3794a1ba"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP CONSTRAINT "FK_de8978490834e2e9cb3c3fc8066"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_a53679287450d522a3f700088e9"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2b34d74ea416e099ba1525da6e6"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_b183972e0b84c9022884433195e"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23"`);
        await queryRunner.query(`ALTER TABLE "friends_requests" DROP CONSTRAINT "FK_e06dd257e072a8aa3c4299ec33e"`);
        await queryRunner.query(`ALTER TABLE "friends_requests" DROP CONSTRAINT "FK_7914ec6460702eabeddbd9b77f8"`);
        await queryRunner.query(`ALTER TABLE "friends" DROP CONSTRAINT "FK_7228831e05ab7a5a7bf260c5ce6"`);
        await queryRunner.query(`ALTER TABLE "friends" DROP CONSTRAINT "FK_23fac43a0543182b1f1bdd644c7"`);
        await queryRunner.query(`ALTER TABLE "reacts" DROP CONSTRAINT "FK_dfa61fb53fdd11941a52f05351e"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_312c63be865c81b922e39c2475e"`);
        await queryRunner.query(`ALTER TABLE "post_statistics" DROP CONSTRAINT "FK_ac42035005eced3155c787015fe"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_6a8198b0a3bf6fd4584bc0932f8"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_259bf9825d9d198608d1b46b0b5"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d"`);
        await queryRunner.query(`ALTER TABLE "comment_statistics" DROP CONSTRAINT "FK_3bbda74aca343bbc36f039330cd"`);
        await queryRunner.query(`ALTER TABLE "pages_users" DROP CONSTRAINT "FK_020256cb575d3ff6302315630b6"`);
        await queryRunner.query(`ALTER TABLE "pages_users" DROP CONSTRAINT "FK_1d9fdc44c36ca56b4f81ca1bf14"`);
        await queryRunner.query(`ALTER TABLE "problems_recruitment_posts" DROP CONSTRAINT "FK_c38fcf53c82ab17f72db6f748cd"`);
        await queryRunner.query(`ALTER TABLE "problems_recruitment_posts" DROP CONSTRAINT "FK_3cd0e939eeacc5e3944a29fff7b"`);
        await queryRunner.query(`ALTER TABLE "problems_users" DROP CONSTRAINT "FK_8776019c9132730ba3af6abe99b"`);
        await queryRunner.query(`ALTER TABLE "problems_users" DROP CONSTRAINT "FK_6bf973a1955c5f27079f446155c"`);
        await queryRunner.query(`ALTER TABLE "problems" DROP CONSTRAINT "FK_d70540d9e2b2264909c84148825"`);
        await queryRunner.query(`ALTER TABLE "recruitment_posts" DROP CONSTRAINT "FK_2a74bde895d01c06cb61456062e"`);
        await queryRunner.query(`ALTER TABLE "applications_problems" DROP CONSTRAINT "FK_7d017d4fe48c00bacc849aaac12"`);
        await queryRunner.query(`ALTER TABLE "applications_problems" DROP CONSTRAINT "FK_f2effc129801d702f1cde963896"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_5a18e8914a1a55ae3be14764bd0"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_9e7594d5b474d9cbebba15c1ae7"`);
        await queryRunner.query(`DROP TABLE "conversation_read_status"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "follows"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_gender_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "participants"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TABLE "friends_requests"`);
        await queryRunner.query(`DROP TABLE "friends"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d95caa497b2292c730dd45d900"`);
        await queryRunner.query(`DROP TABLE "reacts"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP TABLE "post_statistics"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP TABLE "comment_statistics"`);
        await queryRunner.query(`DROP TABLE "pages_users"`);
        await queryRunner.query(`DROP TYPE "public"."pages_users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3edf1d1cf08691a0a432589ac9"`);
        await queryRunner.query(`DROP TABLE "pages"`);
        await queryRunner.query(`DROP TYPE "public"."pages_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ddb83c9599ff3fc19dfef0692c"`);
        await queryRunner.query(`DROP TABLE "assets"`);
        await queryRunner.query(`DROP TABLE "problems_recruitment_posts"`);
        await queryRunner.query(`DROP TABLE "problems_users"`);
        await queryRunner.query(`DROP TABLE "problems"`);
        await queryRunner.query(`DROP TABLE "recruitment_posts"`);
        await queryRunner.query(`DROP TABLE "applications_problems"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18a836fd4614ea6282418239fa"`);
        await queryRunner.query(`DROP TABLE "applications"`);
    }

}
