import { MigrationInterface, QueryRunner } from "typeorm";

export class ChangeToTimezone1743012724343 implements MigrationInterface {
    name = 'ChangeToTimezone1743012724343'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications_problems" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "applications_problems" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications_problems" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "applications_problems" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "recruitment_posts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "recruitment_posts" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "recruitment_posts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "recruitment_posts" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "problems" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "problems" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "problems" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "problems" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "problems_users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "problems_users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "problems_users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "problems_users" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "problems_recruitment_posts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "problems_recruitment_posts" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "problems_recruitment_posts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "problems_recruitment_posts" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pages" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "pages" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pages" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "pages" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pages_users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "pages_users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pages_users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "pages_users" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reacts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "reacts" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reacts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reacts" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "friends" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "friends" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "friends" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "friends" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "friends_requests" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "friends_requests" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "friends_requests" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "friends_requests" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "participants" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "participants" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "participants" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "participants" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "conversation_read_status" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "conversation_read_status" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "conversation_read_status" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "conversation_read_status" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "conversation_read_status" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "conversation_read_status" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "conversation_read_status" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "conversation_read_status" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "participants" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "participants" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "participants" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "participants" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "friends_requests" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "friends_requests" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "friends_requests" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "friends_requests" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "friends" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "friends" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "friends" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "friends" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reacts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reacts" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reacts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "reacts" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pages_users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "pages_users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pages_users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "pages_users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pages" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "pages" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pages" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "pages" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "problems_recruitment_posts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "problems_recruitment_posts" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "problems_recruitment_posts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "problems_recruitment_posts" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "problems_users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "problems_users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "problems_users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "problems_users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "problems" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "problems" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "problems" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "problems" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "recruitment_posts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "recruitment_posts" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "recruitment_posts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "recruitment_posts" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications_problems" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "applications_problems" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications_problems" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "applications_problems" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
    }

}
