version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: infinitys_postgres
    restart: always
    environment:
      POSTGRES_USER: infinitys
      POSTGRES_PASSWORD: infinitys
      POSTGRES_DB: infinitys
    ports:
      - "20251:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: infinitys_redis
    restart: always
    ports:
      - "20252:6379"
    networks:
      - my_network

  minio:
    image: minio/minio
    container_name: minio_container
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "20253:9000"  # MinIO API
      - "20254:9001"  # MinIO Console
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    networks:
      - my_network

  init_minio:
    build:
      context: docker/minio
      dockerfile: Dockerfile
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BUCKET: infinitys
      AWS_S3_ACCESS_KEY_ID: HrNRKvVa2ydc3t9cpsEd
      AWS_S3_SECRET_ACCESS_KEY: ftJDm0nyeHdY2wSqOQE4q5DYa2vVj93lIiZiu0J2
    networks:
      - my_network

volumes:
  postgres_data:
  minio_data:

networks:
  my_network:
    driver: bridge
