version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: infinitys_postgres
    restart: always
    environment:
      POSTGRES_USER: infinitys
      POSTGRES_PASSWORD: infinitys
      POSTGRES_DB: infinitys
    ports:
      - "20251:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: infinitys_redis
    restart: always
    ports:
      - "20252:6379"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
